#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
# Date: October 2017
# Source : http://eigen.tuxfamily.org/dox/GettingStarted.html
## Script to build and install a new package

cd `dirname $0`

SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`
##These config files are relative to
# the Install script working directory
pack_config_file=eigen_package.cfg

if [ ! -f ../Configuration ]
then
  echo "'../Configuration' file missing "     
  exit 1
fi
if [ ! -f $1 ]
then
  echo "'$1' file missing"     
  exit 1
fi

source ./../Configuration
source ./$pack_config_file

if [ ! -f $RELEASE_FILE ]
then
   echo "File $RELEASE_FILE does not exists"
   exit 1
fi

RELEASE_NUMBER=`cat $RELEASE_FILE`
LOG_FILE="${DOWNLOADS_LOG_DIR}/$SCRIPT_NAME.$SHORT_NAME.$RELEASE_NUMBER.log"
PACKAGE_BASE=$LOCAL_DIR/$GIT_REPOS 

rm -rf $LOG_FILE
touch $LOG_FILE

rstatus=""
echo "==" | tee -a $LOG_FILE
echo "Product: $GIT_REPOS" | tee -a $LOG_FILE
echo "Install directory: $PACKAGE_BASE" | tee -a $LOG_FILE
echo "Release version: $RELEASE_NUMBER" | tee -a $LOG_FILE
echo "Install on Server Name: `uname -n`" | tee -a $LOG_FILE
echo "==" | tee -a $LOG_FILE

#Copy libraries to the include path 
if [ ! -d "$PACKAGE_BASE/" ]
then
   echo "$PACKAGE_BASE directory missing" | tee -a $LOG_FILE
   exit 1
fi
cd $PACKAGE_BASE

#Copy libraries  to /opt/software/include
cp -RP  */Eigen $SOFTWARE_BASE/include

exit 0
