#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
# Date: February 2018
#
## Script to build and install a new package
#
# Usage: ./path2/Install tool_name
# Where tool_name is the name of the base directory for this tool
# as defined in the variable SHORT_NAME in the tool config file
#
# Example : ./Install bamtools 
# Different versions of bamtools will be installed under 
# EXTERNAL_SOFTWARE_BASE/bamtools and the current version 
# installed is stored in  EXTERNAL_SOFTWARE_BASE/bamtools/current_release_NUMBER
#
# What it does:
# 1) Calls prep_install script to setup logs and runs the dependency test
# 2) Calls the tool's install script

cd `dirname $0`

SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`

if [ $# -lt 1 ]
then
  echo "Usage: ./${SCRIPT_NAME} tool_name
  echo "Example: ./${SCRIPT_NAME} bamtools 
  exit 1
fi
TOOL_NAME=$1

source ./prep_install ${TOOL_NAME}
source ./${TOOL_NAME}/Install

