#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
# Date: February 2018
#
## Script is called by the Install script 
#  to run the dependency test 
#
# Usage: ./install_check_depends
#
# Assuming all global environment variables needed have
# been set by the parent process
#


cd `dirname $0`

SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`

rstatus=""
echo "==" | tee -a ${LOG_FILE}
echo "Running the dependency test" | tee -a ${LOG_FILE}
echo "Missing dependencies:" | tee -a ${LOG_FILE}

for dependency in $BIN_DEPENDENCIES
do
    token=`which ${dependency}`
    if [ ! -f "${token}" ]
    then
       echo "Dependency: ${dependency}" | tee -a ${LOG_FILE}
       rstatus="Failed"
    fi
done
# Check LIBRARY dependencies
for dependency in $LIB_DEPENDENCIES
do
  tokens=`locate $dependency`
  for lib_path in $tokens
  do
    if [ ! -f ${lib_path} ]
    then
      echo "Dependency: ${dependency} - ${lib_path}" | tee -a $LOG_FILE
      rstatus="Failed"
    fi
  done
done
echo "==" | tee -a ${LOG_FILE}
if [ "$rstatus" == Failed ]
then
  echo "Dependency test Failed" | tee -a ${LOG_FILE}
  exit 1
fi
echo "Dependency test passed" | tee -a ${LOG_FILE}
if [ ! -d ${PACKAGE_BASE} ]
then
   echo "Path to ${GIT_REPOS} install directory not correct. See ${PACKAGE_BASE}" | tee -a ${LOG_FILE}
   exit 1
fi
