#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
# Date: February 2018
#
## Script is called by the Install script 
#  to run the dependency test 
#
# Usage: ./install_check_package_install
#
# Assuming all global environment variables needed have
# been set by the parent process
#


echo "Checking the package install under ${PACKAGE_BASE}" | tee -a ${LOG_FILE}
#Check the install
rstatus="SUCCESS"
for folder in ${DIR_CHECK}
do
    if [ ! -d ${PACKAGE_BASE}/${folder} ]
    then
       echo "${PACKAGE_BASE}/${folder} missing" | tee -a ${LOG_FILE}
       rstatus="FAILED"
     fi
done

if [ "${rstatus}" == FAILED ]
then
   echo "${rstatus}" | tee -a ${LOG_FILE}
   exit 1
fi
echo "Install's Status: ${rstatus} " | tee -a ${LOG_FILE}
exit 0
