#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
# Date: June 2018
# Modified: September 2018
#
# This script is called by the main install script 
# (install_package.sh)  to build and install 
# a new version of the package 
#
# What it does:
# 1) source the main config file to set global path
# 2) source the dependencies config file
# 3) runs the pyhton install command
#
#
#
# Note: the following environment variables are expected to be set
# by the caller
# 1) GLOBAL_CONFIG
# 2) PACKAGE_BASE
# 3) PACKAGE_DEPENDS
#
cd `dirname $0`
SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`
echo "==" 
echo "Server Name: `uname -n`" 
echo "Install Date: `date`" 
if [ ! -f ../${GLOBAL_CONFIG} ]
then
  echo "'../${GLOBAL_CONFIG}' file missing "     
  exit 1
fi
source ./../${GLOBAL_CONFIG}
if [ "${PACKAGE_DEPENDS}" = "" ]
then
   echo "ERROR: PACKAGE_DEPENDS not set"
   exit 1
fi
PACKAGE_DEPENDENCIES_FILE=`basename ${PACKAGE_DEPENDS}`
PACKAGE_CONFIG=`basename ${PACKAGE_CONFIG_FILE}`
source ./${PACKAGE_DEPENDENCIES_FILE}
source ./${PACKAGE_CONFIG}

if [ ! -d ${PACKAGE_BASE} ]
then
   echo "ERROR: Missing the install directory ${PACKAGE_BASE} "
   exit 1
fi

cd $PACKAGE_BASE

python setup.py install --prefix ${SOFTWARE_BASE}

#Check the install

rstatus="SUCCESS"
for pkg_dir in ${DIR_CHECK}
do
    if [ ! -d ${PACKAGE_BASE}/${pkg_dir} ]
    then
       echo "$pkg_dir missing under ${PACKAGE_BASE} "
       rstatus="FAILED"
     fi
done

for pkg_file in ${FILE_CHECK}
do
    if [ ! -f ${PACKAGE_BASE}/${pkg_file} ]
    then
       echo "$pkg_file missing under ${PACKAGE_BASE} "
       rstatus="FAILED"
     fi
done

if [ "${rstatus}" == FAILED ]
then
   echo "${rstatus}" 
   exit 1
fi
echo ${rstatus}
exit 0

