#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
# Date: January 2018
# Modified: February 2018
#
# This script is called by the main install script 
# (install_package.sh)  to build and install 
# a new version of the package 
#
# What it does:
# 1) source the main config file to set global path
# 2) untar the downloaded tar file
# 3) builds and install the package
#
# Note: the following environment variables are expected to be set
# by the caller
# 1) GLOBAL_CONFIG
# 2) PACKAGE_BASE
# 3) PACKAGE_DEPENDS
#
cd `dirname $0`
SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`
echo "==" 
echo "Server Name: `uname -n`" 
echo "Install Date: `date`" 
if [ ! -f ../${GLOBAL_CONFIG} ]
then
  echo "'../${GLOBAL_CONFIG}' file missing "     
  exit 1
fi
source ./../${GLOBAL_CONFIG}
if [ "${PACKAGE_DEPENDS}" = "" ]
then
   echo "ERROR: PACKAGE_DEPENDS not set"
   exit 1
fi
PACKAGE_DEPENDENCIES_FILE=`basename ${PACKAGE_DEPENDS}`
source ./${PACKAGE_DEPENDENCIES_FILE}
if [ ! -d ${PACKAGE_BASE} ]
then
   echo "ERROR: Missing the install directory ${PACKAGE_BASE} "
   exit 1
fi
version=`echo $RELEASE_NUMBER | sed -e 's/^v//' | sed -e 's/^[[:space:]]*//'`
echo "$version"
#Shared installation (on a cluster)
${VIRTUALENV} $PACKAGE_BASE/venv
if [ $? -ne 0 ]
then
  echo "ERROR:'virtualenv ${PACKAGE_BASE}/venv' failed"
  echo "Status: FAILED"
  exit 1
fi
echo "Running 'sudo ${PACKAGE_BASE}/venv/bin/pip install --install-option="--install-scripts=${SOFTWARE_BIN_BASE}"
cutadapt==$version' from `pwd`" 
sudo ${PACKAGE_BASE}/venv/bin/pip install --install-option="--install-scripts=${SOFTWARE_BIN_BASE}" cutadapt==$version
#sudo pip install --upgrade cutadapt
if [ $? -ne 0 ]
then
  echo "Status: FAILED"
  exit 1
fi
echo "Status: SUCCESS"
exit 0

