#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
# MODIFIED: March 2018
#
# This script is called by the main install script 
# (install_package.sh)  to build and install 
# a new version of the package 
#
# What it does:
# 1) source the main config file to set gloabl path
# 2) source the dependencies config file
# 3) source package config file
# 3) build and install package
#
# Note: the following environment variables are expected to be set
# by the caller
# 1) GLOBAL_CONFIG
# 2) PACKAGE_DEPENDS
# 3) PACKAGE_CONFIG_FILE
#
cd `dirname $0`
SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`

echo "==" 
echo "Server Name: `uname -n`" 
echo "Install Date: `date`" 
if [ ! -f ../${GLOBAL_CONFIG} ]
then
  echo "'../${GLOBAL_CONFIG}' file missing "     
  exit 1
fi
source ./../${GLOBAL_CONFIG}
if [ "${PACKAGE_DEPENDS}" = "" ]
then
   echo "ERROR: PACKAGE_DEPENDS not set"
   exit 1
fi
PACKAGE_DEPENDENCIES_FILE=`basename ${PACKAGE_DEPENDS}`
source ./${PACKAGE_DEPENDENCIES_FILE}
toil_config=`basename ${PACKAGE_CONFIG_FILE}`

if [ ! -f ${toil_config} ]
then
  echo "'${toil_config}' file missing under `pwd` "     
  exit 1
fi
source ./${toil_config}

#Create virtualenv directory for this repos as needed
if [ ! -d ${TOIL_BASE} ]
then
    mkdir -p ${TOIL_BASE}
    ${VIRTUALENV} -p ${PYTHON} ${TOIL_BASE}
fi
#
# activate virtualenv
source $TOIL_BASE/bin/activate

${PIP} install toil 2>&1 
${PIP} install toil cwl 2>&1 

#Check the install
rstatus="SUCCESS"
for bin_file in ${FILE_CHECK}
do
    if [ ! -f ${TOIL_BASE}/bin/${bin_file} ]
    then
       echo "${TOIL_BASE}/bin/${bin_file} missing"
       rstatus="FAILED"
     fi
done

if [ "$rstatus" == FAILED ]
then
   echo "$rstatus" 
   exit 1
fi
#exit virtualenv
#
deactivate
#make clean
exit 0

