#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
# Date: January 2018
# Source : http://hannonlab.cshl.edu/fastx_toolkit/install_centos.txt
## Script to build and install a new package

cd `dirname $0`

SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`
##These config files are relative to
# the Install script working directory
dependents_file=dependencies.cfg
pack_config_file=fastx_toolkit_repos.cfg

if [ ! -f $dependents_file ]
then
   echo "The dependencies file: $dependents_file is missing"
   echo " From $WORKING_DIR"
   exit 1
fi
if [ ! -f ../Configuration ]
then
  echo "'../Configuration' file missing "     
  exit 1
fi
if [ ! -f $1 ]
then
  echo "'$1' file missing"     
  exit 1
fi

source ./../Configuration
source ./$dependents_file
source ./$pack_config_file

if [ ! -f $RELEASE_FILE ]
then
   echo "File $RELEASE_FILE does not exists"
   exit 1
fi

RELEASE_NUMBER=`cat $RELEASE_FILE`
LOG_FILE="${DOWNLOADS_LOG_DIR}/$SCRIPT_NAME.$SHORT_NAME.$RELEASE_NUMBER.log"
PACKAGE_BASE=$LOCAL_DIR/$SHORT_NAME

rm -rf $LOG_FILE
touch $LOG_FILE

rstatus=""
echo "==" | tee -a $LOG_FILE
echo "Product: $GIT_REPOS" | tee -a $LOG_FILE
echo "Install directory: $PACKAGE_BASE" | tee -a $LOG_FILE
echo "Release version: $RELEASE_NUMBER" | tee -a $LOG_FILE
echo "Install on Server Name: `uname -n`" | tee -a $LOG_FILE
echo "==" | tee -a $LOG_FILE

echo "Running the dependency test" | tee -a $LOG_FILE
echo "Missing dependencies:" | tee -a $LOG_FILE
for dependency in $DEPENDENCIES
do
    token=`which $dependency`
    if [ ! -f "$token" ]
    then
       echo "Dependency: $dependency" | tee -a $LOG_FILE
       rstatus="Failed"
    fi
done
# Check Lib dependency
for dependency in $LIB_DEPENDENCIES
do
  tokens=`locate $dependency`
  for lib_path in $tokens
  do
    if [ ! -f $lib_path ]
    then
      echo "Dependency: $dependency" | tee -a $LOG_FILE
      rstatus="Failed"
    fi
  done
done
echo "==" | tee -a $LOG_FILE
if [ "$rstatus" == Failed ]
then
  echo "Dependency test Failed" | tee -a $LOG_FILE
  exit 1
fi
echo "Dependency test passed" | tee -a $LOG_FILE
echo "Checking the Install directory:" | tee -a $LOG_FILE
# Execute the Install command for this package
#
if [ ! -d $PACKAGE_BASE ]
then
  echo "ERROR:$PACKAGE_BASE directory missing" | tee -a $LOG_FILE    
  echo "Status: FAILED" | tee -a $LOG_FILE
  exit 1
fi
#Check the install
cd $PACKAGE_BASE 
if [ ! -f configure ]
then
  echo "ERROR:$PACKAGE_BASE/configure file missing"| tee -a $LOG_FILE
  echo "Status: FAILED"| tee -a $LOG_FILE
  exit 1
fi

export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig"

echo "Running ./configure from `pwd`" | tee -a $LOG_FILE
./configure
if [ $? -ne 0 ]
then
  echo "ERROR:Configure failed"
  echo "Status: FAILED"| tee -a $LOG_FILE
  exit 1
fi
echo "Running make from `pwd`" | tee -a $LOG_FILE
make
if [ $? -ne 0 ]
then
  echo "ERROR:make failed"
  echo "Status: FAILED"| tee -a $LOG_FILE
  exit 1
fi
echo "Running 'sudo make install exec_prefix=$SOFTWARE_BASE' from `pwd`" | tee -a $LOG_FILE
#sudo make install
sudo make install exec_prefix=$SOFTWARE_BASE

if [ $? -ne 0 ]
then
  echo "ERROR:'sudo make install exec_prefix=$SOFTWARE_BASE' failed"
  echo "Status: FAILED"| tee -a $LOG_FILE
  exit 1
fi
echo "Status: SUCCESS"
exit 0

