#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
# Date: January 2018
# Modified: February 2018
#
# This script is called by the main install script 
# (install_package.sh)  to build and install 
# a new version of the package 
#
# What it does:
# 1) source the main config file to set global path
# 2) export PKG_CONFIG_PATH
# 3) build and intall the package 
#
# Note: the following environment variables are expected to be set
# by the caller
# 1) GLOBAL_CONFIG
# 2) PACKAGE_BASE
# 3) PACKAGE_DEPENDS
#
cd `dirname $0`
SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`
echo "==" 
echo "Server Name: `uname -n`" 
echo "Install Date: `date`" 
if [ ! -f ../${GLOBAL_CONFIG} ]
then
  echo "'../${GLOBAL_CONFIG}' file missing "     
  exit 1
fi
source ./../${GLOBAL_CONFIG}
if [ "${PACKAGE_DEPENDS}" = "" ]
then
   echo "ERROR: PACKAGE_DEPENDS not set"
   exit 1
fi
PACKAGE_DEPENDENCIES_FILE=`basename ${PACKAGE_DEPENDS}`
source ./${PACKAGE_DEPENDENCIES_FILE}
if [ ! -d ${PACKAGE_BASE} ]
then
   echo "ERROR: Missing the install directory ${PACKAGE_BASE} "
   exit 1
fi
#Check the install
cd ${PACKAGE_BASE} 
if [ ! -f configure ]
then
  echo "ERROR:${PACKAGE_BASE}/configure file missing"
  echo "Status: FAILED"
  exit 1
fi

export PKG_CONFIG_PATH

echo "Running ./configure from `pwd`"
./configure
if [ $? -ne 0 ]
then
  echo "ERROR:Configure failed"
  echo "Status: FAILED"
  exit 1
fi
echo "Running make from `pwd`" | tee -a $LOG_FILE
make
if [ $? -ne 0 ]
then
  echo "ERROR:make failed"
  echo "Status: FAILED"| tee -a $LOG_FILE
  exit 1
fi
echo "Running 'sudo make install exec_prefix=${SOFTWARE_BASE}' from `pwd`" 
#sudo make install
sudo make install exec_prefix=${SOFTWARE_BASE}

if [ $? -ne 0 ]
then
  echo "ERROR:'sudo make install exec_prefix=${SOFTWARE_BASE}' failed"
  echo "Status: FAILED"
  exit 1
fi
echo "Status: SUCCESS"
exit 0

