#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
# Date: October 2017
# Modified: March 2018
#
# This script is called by the main install script 
# (install_package.sh)  to build and install 
# a new version of the package 
#
# What it does:
# 1) source the main config file to set global path
# 2) configure and build the package
# 3) install the package
#
# Note: the following environment variables are expected to be set
# by the caller
# 1) GLOBAL_CONFIG
# 2) PACKAGE_BASE
# 3) PACKAGE_DEPENDS
#
cd `dirname $0`
SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`
echo "==" 
echo "Server Name: `uname -n`" 
echo "Install Date: `date`" 
if [ ! -f ../${GLOBAL_CONFIG} ]
then
  echo "'../${GLOBAL_CONFIG}' file missing "     
  exit 1
fi
source ./../${GLOBAL_CONFIG}
if [ "${PACKAGE_DEPENDS}" = "" ]
then
   echo "ERROR: PACKAGE_DEPENDS not set"
   exit 1
fi
PACKAGE_DEPENDENCIES_FILE=`basename ${PACKAGE_DEPENDS}`
source ./${PACKAGE_DEPENDENCIES_FILE}
if [ ! -d ${PACKAGE_BASE} ]
then
   echo "ERROR: Missing the install directory ${PACKAGE_BASE} "
   exit 1
fi
cd ${PACKAGE_BASE}
#
#update path to binaries to /opt/software/bin
sed -i -e  's@prefix =[[:space:]].*@'"prefix =  ${SOFTWARE_BASE}"'@' Makefile

make allall 2>&1
#Check the install
rstatus="SUCCESS"
for bin_file in ${FILE_CHECK}
do
    if [ ! -f ${PACKAGE_BASE}/$bin_file ]
    then
       echo "${PACKAGE_BASE}/$bin_file missing"
       rstatus="FAILED"
     fi
done

if [ "$rstatus" == FAILED ]
then
   echo "$rstatus"
   exit 1
fi
echo $rstatus 
#Copy binaries to /opt/software/bin
make install
#make clean
exit 0

