#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
# Date: November 2017
# Modified: February 2018
#
# This script is called by the main install script 
# (install_package.sh)  to build and install 
# a new version of the package 
#
# What it does:
# 1) source the main config file to set global path
# 2) Move content from temp directory to PACKAGE_BASE
# 3) Copy binaries and libraries to /opt/software/bin and /opt/software/lib
#
# Note: the following environment variables are expected to be set
# by the caller
# 1) GLOBAL_CONFIG
# 2) PACKAGE_BASE
# 3) PACKAGE_DEPENDS
# 4) PACKAGE_CONFIG_FILE 
#
cd `dirname $0`
SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`
echo "==" 
echo "Server Name: `uname -n`" 
echo "Install Date: `date`" 
if [ ! -f ../${GLOBAL_CONFIG} ]
then
  echo "'../${GLOBAL_CONFIG}' file missing "     
  exit 1
fi
source ./../${GLOBAL_CONFIG}
if [ "${PACKAGE_DEPENDS}" = "" ]
then
   echo "ERROR: PACKAGE_DEPENDS not set"
   exit 1
fi
PACKAGE_DEPENDENCIES_FILE=`basename ${PACKAGE_DEPENDS}`
PACKAGE_CONFIG=`basename ${PACKAGE_CONFIG_FILE}`
source ./${PACKAGE_DEPENDENCIES_FILE}
source ./${PACKAGE_CONFIG}
if [ ! -d ${PACKAGE_BASE} ]
then
   echo "ERROR: Missing the install directory ${PACKAGE_BASE} "
   exit 1
fi

##move content to this version root directory 
[ -d ${PACKAGE_BASE}/${TEMP_DOWNLOAD_DIR} ] && mv ${PACKAGE_BASE}/${TEMP_DOWNLOAD_DIR}/* ${PACKAGE_BASE}/ 

#Check the install
rstatus="SUCCESS"
for dir in ${DIR_CHECK}
do
    if [ ! -d ${PACKAGE_BASE}/${dir} ]
    then
       echo "${PACKAGE_BASE}/${dir} missing"
       rstatus="FAILED"
     fi
done

if [ "${rstatus}" == FAILED ]
then
   echo "${rstatus}" 
   exit 1
fi
echo ${rstatus} 
#Copy binaries and libraries to /opt/software/bin and /opt/software/lib
for dir in ${DIR_CHECK}
do
    cp -P  ${PACKAGE_BASE}/${dir}/* ${SOFTWARE_BASE}/${dir}/
done

exit 0

