#!/usr/bin/sh
#
# Organization: MDIBL
# Author: Lucie Hutchins
# Date: September 2017
#
#A simple script that downloads and stores locally the current release
# FOOTER.txt file 
#
# What it does:
#  1) downloads the current release Readme file (FOOTER.txt)
#  2) sets the current release number flag
#
# This will be scheduled on Jenkins to run dailly
#
cd `dirname $0`

SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`
SRC_CONFIG_BASE=`realpath $WORKING_DIR`
SRC_CONFIG=orthodb.cfg
README_CONFIG=www.orthodb.org.current_readme.cfg
CURRENT_README=FOOTER.txt
DOWNLOAD_SCRIPT=download_package
CURRENT_RELEASE_FLAG=current_release_NUMBER

if [ ! -f ../Configuration ]
then
  echo "'Configuration' file missing "     
  exit 1
fi
if [ ! -f $SRC_CONFIG ]
then
  echo "'$SRC_CONFIG' file missing under $WORKING_DIR"     
  exit 1
fi

source ../Configuration
source ./$SRC_CONFIG
source ./$README_CONFIG

readme_config_path="$SHORT_NAME/$README_CONFIG"
SRC_BASE="$EXTERNAL_DATA_BASE/$SHORT_NAME"
#setup the log
LOG_FILE="${DOWNLOADS_LOG_DIR}/$SCRIPT_NAME.log"

rm -rf $LOG_FILE
touch $LOG_FILE

date | tee -a $LOG_FILE
echo "**********              *******************" | tee -a $LOG_FILE
echo " Checking Current Release Number"| tee -a $LOG_FILE
echo "**********  *******************************"| tee -a $LOG_FILE
echo ""| tee -a $LOG_FILE
echo " LOGS"| tee -a $LOG_FILE
echo "Logs generated by this script are under ${DOWNLOADS_LOG_DIR}"| tee -a $LOG_FILE
echo "Log: $SCRIPT_NAME.log"| tee -a $LOG_FILE
echo "Log: $README_CONFIG.log"| tee -a $LOG_FILE
echo ""| tee -a $LOG_FILE
echo " FILES"| tee -a $LOG_FILE
echo "Source Config files and script Files are under ${SRC_CONFIG_BASE}"| tee -a $LOG_FILE
echo "Files generated by this script are under ${SRC_BASE}"| tee -a $LOG_FILE
echo "File: current_README"| tee -a $LOG_FILE


export SRC_CONFIG_BASE

./../$DOWNLOAD_SCRIPT $readme_config_path

if [ ! -f ${SRC_BASE}/$CURRENT_README ]
then
   echo "Download failed: ${SRC_BASE}/$CURRENT_README is missing" 
   exit 1
fi
## Create the current release Number file
release_flag=${SRC_BASE}/$CURRENT_RELEASE_FLAG

touch $release_flag
echo "$RELEASE_NUMBER" > $release_flag

echo "Current Release Number:$RELEASE_NUMBER"| tee -a $LOG_FILE
echo ""| tee -a $LOG_FILE
echo "Program complete"| tee -a $LOG_FILE


echo "********** System dump *******************"| tee -a $LOG_FILE
echo " ENVIRONMENT VARIABLES DUMP"| tee -a $LOG_FILE
echo "**********  *******************************"| tee -a $LOG_FILE
env | sort | tee -a $LOG_FILE
exit 0
