#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
# Date: October 2017
#
# This script is called by the main install script 
# (install_package.sh)  to build and install 
# a new version of the package 
#
# What it does:
# 1) source the main config file to set gloabl path
# 2) source the dependencies config file
# 3) copy  the executables to /opt/software/bin
#
#
# Note: the following environment variables are expected to be set
# by the caller
# 1) GLOBAL_CONFIG
# 2) PACKAGE_BASE
# 3) PACKAGE_DEPENDS
#
cd `dirname $0`
SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`
echo "==" 
echo "Server Name: `uname -n`" 
echo "Install Date: `date`" 
if [ ! -f ../${GLOBAL_CONFIG} ]
then
  echo "'../${GLOBAL_CONFIG}' file missing "     
  exit 1
fi
source ./../${GLOBAL_CONFIG}
if [ "${PACKAGE_DEPENDS}" = "" ]
then
   echo "ERROR: PACKAGE_DEPENDS not set"
   exit 1
fi
PACKAGE_DEPENDENCIES_FILE=`basename ${PACKAGE_DEPENDS}`
source ./${PACKAGE_DEPENDENCIES_FILE}
if [ ! -d ${PACKAGE_BASE} ]
then
   echo "ERROR: Missing the install directory ${PACKAGE_BASE} "
   exit 1
fi
#Copy the binaries to /opt/software/bin
#
for bin_file in ${FILE_CHECK}
do
    if [ ! -f ${PACKAGE_BASE}/${bin_file} ]
    then
        echo "${bin_file} missing under ${PACKAGE_BASE}"
        rstatus="FAILED"
    else
        chmod 755 ${PACKAGE_BASE}/${bin_file}
        echo "cp -p  ${PACKAGE_BASE}/${bin_file} ${SOFTWARE_BIN_BASE}"
        cp -p  ${PACKAGE_BASE}/${bin_file} ${SOFTWARE_BIN_BASE}
    fi
done
echo "${rstatus}" 
[ "${rstatus}" == FAILED ] && exit 1

exit 0

