#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
# Date: October 2017
## Script to build and install a new R package
# What it does:
# 1) source the main config file to set gloabl path
# 2) untar the downloaded tar file
# 3) builds and install R
#
# Note: the following environment variables are expected to be set
#       by the caller
# 1) GLOBAL_CONFIG
# 2) RELEASE_NUMBER
# 3) PACKAGE_DEPENDS
#
cd `dirname $0`

SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`
tool_name=blat
echo "==" 
echo "Server Name: `uname -n`" 
echo "Install Date: `date`" 
if [ ! -f ../${GLOBAL_CONFIG} ]
then
  echo "'../${GLOBAL_CONFIG}' file missing "     
  exit 1
fi
source ./../${GLOBAL_CONFIG}
PACKAGE_CONFIG_FILE=${tool_name}${PACKAGE_CONFIGFILE_SUFFIX}
source ./${PACKAGE_CONFIG_FILE}
PACKAGE_BASE=${EXTERNAL_SOFTWARE_BASE}/${SHORT_NAME}
if [ ! -d ${PACKAGE_BASE}/${RELEASE_DIR} ]
then
   echo "ERROR: Missing the install directory ${PACKAGE_BASE}/${RELEASE_DIR} "
   exit 1
fi
LOG_FILE="${DOWNLOADS_LOG_DIR}/${SCRIPT_NAME}.${SHORT_NAME}.${RELEASE_NUMBER}.log"

rm -rf ${LOG_FILE}
touch ${LOG_FILE}
rstatus=""
echo "==" | tee -a ${LOG_FILE}
echo "Product: ${SHORT_NAME}" | tee -a ${LOG_FILE}
echo "Install directory: ${PACKAGE_BASE}" | tee -a ${LOG_FILE}
echo "Release version: ${RELEASE_NUMBER}" | tee -a ${LOG_FILE}
echo "Install on Server Name: `uname -n`" | tee -a ${LOG_FILE}
echo "==" | tee -a ${LOG_FILE}
cd ${PACKAGE_BASE}/${RELEASE_DIR}
dependencies=`basename ${PACKAGE_DEPENDS}`
if [ ! -f ${dependencies} ]
then
    echo "ERROR: Missing dependency file ${dependencies} under `pwd`"
    exit 1
fi
source ./${dependencies}
#Copy the binaries to /opt/software/bin
#
for bin_file in ${FILE_CHECK}
do
    if [ ! -f ${bin_file} ]
    then
        echo "${bin_file} missing"
        rstatus="FAILED"
    else
        chmod 755 ${bin_file}
        cp -p  ${bin_file} ${SOFTWARE_BASE}/bin/
    fi
done
echo "${rstatus}" 
[ "${rstatus}" == FAILED ] && exit 1

exit 0

