#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
# Date: October 2017
## Script to build and install a new package

cd `dirname $0`

SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`
##These config files are relative to
# the Install script working directory
pack_config_file=blat_package.cfg

if [ ! -f ../Configuration ]
then
  echo "'../Configuration' file missing "     
  exit 1
fi
if [ ! -f $1 ]
then
  echo "'$1' file missing"     
  exit 1
fi

source ./../Configuration
source ./$pack_config_file

if [ ! -f ${RELEASE_FILE} ]
then
   echo "File ${RELEASE_FILE} does not exists"
   exit 1
fi

RELEASE_NUMBER=`cat ${RELEASE_FILE}`
LOG_FILE="${DOWNLOADS_LOG_DIR}/$SCRIPT_NAME.$SHORT_NAME.$RELEASE_NUMBER.log"
PACKAGE_BASE=$LOCAL_DIR

rm -rf $LOG_FILE
touch $LOG_FILE

rstatus=""
echo "==" | tee -a $LOG_FILE
echo "Product: $SHORT_NAME" | tee -a $LOG_FILE
echo "Install directory: $PACKAGE_BASE" | tee -a $LOG_FILE
echo "Release version: $RELEASE_NUMBER" | tee -a $LOG_FILE
echo "Install on Server Name: `uname -n`" | tee -a $LOG_FILE
echo "==" | tee -a $LOG_FILE
if [ ! -d $PACKAGE_BASE ]
then
   echo "Path to install directory not correct. See $PACKAGE_BASE" | tee -a $LOG_FILE
   exit 1
fi

cd $PACKAGE_BASE
#Check the install
rstatus="SUCCESS"
for bin_file in $REMOTE_FILES
do
    if [ ! -f $PACKAGE_BASE/$bin_file ]
    then
       echo "$PACKAGE_BASE/$bin_file missing" | tee -a $LOG_FILE
       rstatus="FAILED"
     fi
done
if [ "$rstatus" == FAILED ]
then
   echo "$rstatus" | tee -a $LOG_FILE
   exit 1
fi
echo $rstatus | tee -a $LOG_FILE
#
#Copy the binaries to /opt/software/bin
#
for bin_file in $REMOTE_FILES
do
   chmod 755 $bin_file
   cp  $bin_file $SOFTWARE_BASE/bin
done
#
# Update symbolic link of this package to point to
# the downloaded version
#
cd $PACKAGE_DOWNLOADS_BASE
rm -f $SHORT_NAME
ln -s ${RELEASE_DIR} $SHORT_NAME

exit 0

