#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
#
# What it does:
# 1) source the main config file to set gloabl path
# 2) source the dependencies config file
# 3) copy the new blat executables to /opt/software/bin
#
# Note: the following environment variables are expected to be set
#       by the caller
# 1) GLOBAL_CONFIG
# 2) RELEASE_NUMBER
# 3) PACKAGE_DEPENDS
#
cd `dirname $0`

SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`
tool_name=hisat2

echo "==" 
echo "Server Name: `uname -n`" 
echo "Install Date: `date`" 
if [ ! -f ../${GLOBAL_CONFIG} ]
then
  echo "'../${GLOBAL_CONFIG}' file missing "     
  exit 1
fi
source ./../${GLOBAL_CONFIG}
PACKAGE_CONFIG_FILE=${tool_name}${PACKAGE_CONFIGFILE_SUFFIX}
source ./${PACKAGE_CONFIG_FILE}
PACKAGE_BASE=${EXTERNAL_SOFTWARE_BASE}/${SHORT_NAME}/${RELEASE_DIR}
depends=`basename ${PACKAGE_DEPENDS}`
if [ ! -f ${depends} ]
then
   echo "ERROR: dependencies.cfg file missing"
   exit 1
fi
source ./${depends}
if [ ! -d ${PACKAGE_BASE} ]
then
   echo "ERROR: Missing the install directory ${PACKAGE_BASE} "
   exit 1
fi
LOG_FILE="${DOWNLOADS_LOG_DIR}/${SCRIPT_NAME}.${SHORT_NAME}.${RELEASE_NUMBER}.log"
rm -rf ${LOG_FILE}
touch ${LOG_FILE}
rstatus=""
echo "==" | tee -a ${LOG_FILE}
echo "Product: ${SHORT_NAME}" | tee -a ${LOG_FILE}
echo "Install directory: ${PACKAGE_BASE}" | tee -a ${LOG_FILE}
echo "Release version: ${RELEASE_NUMBER}" | tee -a ${LOG_FILE}
echo "Install on Server Name: `uname -n`" | tee -a ${LOG_FILE}
echo "==" | tee -a ${LOG_FILE}

cd $PACKAGE_BASE
#
make  2>&1 
#Check the install
rstatus="SUCCESS"
for bin_file in ${FILE_CHECK}
do
    if [ ! -f ${PACKAGE_BASE}/${bin_file} ]
    then
       echo "$PACKAGE_BASE/$bin_file missing" 
       rstatus="FAILED"
     fi
done
if [ "${rstatus}" == FAILED ]
then
   echo "${rstatus}" 
   exit 1
fi
echo ${rstatus}
#Copy binaries to /opt/software/bin
for bin_file in $FILE_CHECK
do
    cp -P  $PACKAGE_BASE/$bin_file $SOFTWARE_BASE/bin
done
#make clean
exit 0

