#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
#
# What it does:
# 1) source the main config file to set gloabl path
# 2) source the dependencies config file
# 3) runs the build and copy  the executables to /opt/software/bin
#
# Note: the following environment variables are expected to be set
#       by the caller
# 1) GLOBAL_CONFIG
# 2) PACKAGE_BASE
#
cd `dirname $0`

SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`
echo "==" 
echo "Server Name: `uname -n`" 
echo "Install Date: `date`" 
if [ ! -f ../${GLOBAL_CONFIG} ]
then
  echo "'../${GLOBAL_CONFIG}' file missing "     
  exit 1
fi
source ./../${GLOBAL_CONFIG}
if [ ! -f ${PACKAGE_DEPENDENCIES_FILE} ]
then
   echo "ERROR: ${PACKAGE_DEPENDENCIES_FILE} file missing"
   exit 1
fi
source ./${PACKAGE_DEPENDENCIES_FILE}
if [ ! -d ${PACKAGE_BASE} ]
then
   echo "ERROR: Missing the install directory ${PACKAGE_BASE} "
   exit 1
fi
cd $PACKAGE_BASE
#
make  2>&1 
#Check the install
rstatus="SUCCESS"
for bin_file in ${FILE_CHECK}
do
    if [ ! -f ${bin_file} ]
    then
       echo "$bin_file missing" 
       rstatus="FAILED"
     fi
done
if [ "${rstatus}" == FAILED ]
then
   echo "${rstatus}" 
   exit 1
fi
echo ${rstatus}
#Copy binaries to /opt/software/bin
for bin_file in $FILE_CHECK
do
    chmod 755 ${bin_file}
    echo "cp -p  ${bin_file} ${SOFTWARE_BASE}/bin/"
    cp -P  $bin_file $SOFTWARE_BASE/bin
done
#make clean
exit 0

