#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
# Date: October 2017
# Modified: February 2018
#
# This script is called by the main install script 
# (install_package.sh)  to build and install 
# a new version of the package 
#
# What it does:
# 1) source the main config file to set global path
# 2) runs the build and copy  the executables to /opt/software/bin
#
#
# Note: the following environment variables are expected to be set
# by the caller
# 1) GLOBAL_CONFIG
# 2) PACKAGE_BASE
#
cd `dirname $0`
SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`
echo "==" 
echo "Server Name: `uname -n`" 
echo "Install Date: `date`" 
if [ ! -f ../${GLOBAL_CONFIG} ]
then
  echo "'../${GLOBAL_CONFIG}' file missing "     
  exit 1
fi
source ./../${GLOBAL_CONFIG}
if [ ! -d ${PACKAGE_BASE} ]
then
   echo "ERROR: Missing the install directory ${PACKAGE_BASE} "
   exit 1
fi
cd $PACKAGE_BASE
#
#update path to binaries to /opt/software/bin
./bootstrap.sh --prefix=$SOFTWARE_BASE  2>&1
#Check the install
if [ $? -ne 0 ]; then
      echo
      echo "./bootsrap.sh Failed." 
      echo "Consult $LOG_FILE for more details"
      exit 1
fi
./bjam --prefix=$SOFTWARE_BASE link=static runtime-link=static stage install 2>&1 
if [ $? -ne 0 ]; then
      echo ""
      echo "'./bjam --prefix=${SOFTWARE_BASE} link=static runtime-link=static stage install' Failed." 
      echo "Consult $LOG_FILE for more details"
      exit 1
fi
BOOST_DIR=${SOFTWARE_BASE}/include/boost
if [ ! -d ${BOOST_DIR} ]; then
   echo "Install failed: missing directory - ${BOOST_DIR}"
   exit 1
fi
cd ${BOOST_DIR}
mkdir tr1
cp *.hpp tr1

exit 0

