#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
# Date: October 2017
# Modified: February 2018
#
# This script is called by the main install script 
# (install_package.sh)  to build and install 
# a new version of the package 
#
# What it does:
# 1) source the main config file to set global path
# 2) configure and build the package
# 3) install the package
#
# Note: the following environment variables are expected to be set
# by the caller
# 1) PACKAGE_BASE
# 
cd `dirname $0`
SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`
echo "==" 
echo "Server Name: `uname -n`" 
echo "Install Date: `date`" 
if [ "${PACKAGE_BASE}" = "" ]
then
  echo " PACKAGE_BASE environmen variable not set "     
  exit 1
fi
cd $PACKAGE_BASE
rstatus="SUCCESS"
#
#update path to binaries to /opt/software/bin
#Check the install
BUILD_TYPE=debug
#BUILD_TYPE=static
LIB_TYPE=shared
#LIB_TYPE=release
#meson --buildtype ${BUILD_TYPE} --default-library ${LIB_TYPE} . build-${LIB_TYPE}
#ninja -v -C build-${LIB_TYPE} test
mkdir -p build/debug
cd build/debug
cmake -DCMAKE_BUILD_TYPE=debug -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF -DARCHIVE_INSTALL_DIR=. -G "Unix Makefiles" ../..
make
exit 0

