#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
# Date: October 2017
## Script to build and install a new package

cd `dirname $0`

SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`
##These config files are relative to
# the Install script working directory
dependents_file=dependencies.cfg
pack_config_file=jsoncpp_package.cfg

if [ ! -f $dependents_file ]
then
   echo "The dependencies file: $dependents_file is missing"
   echo " From $WORKING_DIR"
   exit 1
fi
if [ ! -f ../Configuration ]
then
  echo "'../Configuration' file missing "     
  exit 1
fi
if [ ! -f $1 ]
then
  echo "'$1' file missing"     
  exit 1
fi

source ./../Configuration
source ./$dependents_file
source ./$pack_config_file

if [ ! -f ${LOCAL_DIR}/current_release_NUMBER ]
then
   echo "File ${LOCAL_DIR}/current_release_NUMBER does not exists"
   exit 1
fi

RELEASE_NUMBER=`cat ${LOCAL_DIR}/current_release_NUMBER`
LOG_FILE="${DOWNLOADS_LOG_DIR}/$SCRIPT_NAME.$SHORT_NAME.$RELEASE_NUMBER.log"
PACKAGE_BASE=$LOCAL_DIR/$GIT_REPOS 

rm -rf $LOG_FILE
touch $LOG_FILE

rstatus=""
echo "==" | tee -a $LOG_FILE
echo "Product: $GIT_REPOS" | tee -a $LOG_FILE
echo "Install directory: $PACKAGE_BASE" | tee -a $LOG_FILE
echo "Release version: $RELEASE_NUMBER" | tee -a $LOG_FILE
echo "Install on Server Name: `uname -n`" | tee -a $LOG_FILE
echo "==" | tee -a $LOG_FILE

echo "Running the dependency test" | tee -a $LOG_FILE
echo "Missing dependencies:" | tee -a $LOG_FILE
for dependency in $DEPENDENCIES
do
    token=`which $dependency`
    if [ ! -f "$token" ]
    then
       echo "Dependency: $dependency" | tee -a $LOG_FILE
       rstatus="Failed"
    fi
done
# Check Lib dependency
for dependency in $LIB_DEPENDENCIES
do
  tokens=`locate $dependency`
  for lib_path in $tokens
  do
    if [ ! -f $lib_path ]
    then
      echo "Dependency: $dependency" | tee -a $LOG_FILE
      rstatus="Failed"
    fi
  done
done

echo "==" | tee -a $LOG_FILE
if [ "$rstatus" == Failed ]
then
  echo "Dependency test Failed" | tee -a $LOG_FILE
  exit 1
fi
echo "Dependency test passed" | tee -a $LOG_FILE

# Execute the Install command for this package
if [ ! -d $PACKAGE_BASE ]
then
   echo "Path to $GIT_REPOS install directory not correct. See $PACKAGE_BASE" | tee -a $LOG_FILE
   exit 1
fi

cd $PACKAGE_BASE
rstatus="SUCCESS"
#
#update path to binaries to /opt/software/bin
#Check the install
BUILD_TYPE=debug
#BUILD_TYPE=static
LIB_TYPE=shared
#LIB_TYPE=release
#meson --buildtype ${BUILD_TYPE} --default-library ${LIB_TYPE} . build-${LIB_TYPE}
#ninja -v -C build-${LIB_TYPE} test
mkdir -p build/debug
cd build/debug
cmake -DCMAKE_BUILD_TYPE=debug -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF -DARCHIVE_INSTALL_DIR=. -G "Unix Makefiles" ../..
make
exit 0

