#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
# Date: September 2017
# Source : http://bedtools.readthedocs.io/en/stable/content/installation.html
## Script to build and install a new package

cd `dirname $0`

SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`
##The config file is relative to
# the root directory of pacakage download 

if [ ! -f ${GLOBAL_CONFIG} ]
then
  echo "'${GLOBAL_CONFIG}' file missing under `pwd`" 
  echo "You must run the setup.sh script first to generate this file"
  echo "Usage: ./setup.sh "
  exit 1
fi
if [ $# -lt 1 ]
then
  echo "Usage: ./path2/${SCRIPT_NAME} tool_name
  echo "Example: ./${SCRIPT_NAME} bamtools 
  exit 1
fi
TOOL_NAME=$1
source ./${GLOBAL_CONFIG}
PACKAGE_CONFIG_FILE={TOOL_NAME}${PACKAGE_CONFIGFILE_SUFFIX}

source ./${PACKAGE_DEPENDENCIES_FILE}
source ./${PACKAGE_CONFIG_FILE}

if [ ! -f ${RELEASE_FILE} ]
then
   echo "File ${RELEASE_FILE} does not exists"
   exit 1
fi
RELEASE_NUMBER=`cat ${RELEASE_FILE}`
LOG_FILE="${DOWNLOADS_LOG_DIR}/$SCRIPT_NAME.$SHORT_NAME.$RELEASE_NUMBER.log"
PACKAGE_BASE=$LOCAL_DIR/$GIT_REPOS 

rm -rf $LOG_FILE
touch $LOG_FILE

rstatus=""
echo "==" | tee -a $LOG_FILE
echo "Product: $GIT_REPOS" | tee -a $LOG_FILE
echo "Install directory: $PACKAGE_BASE" | tee -a $LOG_FILE
echo "Release version: $RELEASE_NUMBER" | tee -a $LOG_FILE
echo "Install on Server Name: `uname -n`" | tee -a $LOG_FILE
echo "==" | tee -a $LOG_FILE
echo "Running the dependency test" | tee -a $LOG_FILE
echo "Missing dependencies:" | tee -a $LOG_FILE
for dependency in $DEPENDENCIES
do
    token=`which $dependency`
    if [ ! -f "$token" ]
    then
       echo "Dependency: $dependency" | tee -a $LOG_FILE
       rstatus="Failed"
    fi
done
echo "==" | tee -a $LOG_FILE
if [ "$rstatus" == Failed ]
then
  echo "Dependency test Failed" | tee -a $LOG_FILE
  exit 1
fi
echo "Dependency test passed" | tee -a $LOG_FILE

# Execute the Install command for this package
if [ ! -d $PACKAGE_BASE ]
then
   echo "Path to $GIT_REPOS install directory not correct. See $PACKAGE_BASE" | tee -a $LOG_FILE
   exit 1
fi

cd $PACKAGE_BASE
make 2>&1 | tee -a $LOG_FILE
cd ..
#Check the install
rstatus="SUCCESS"
for folder in $DIR_CHECK
do
    if [ ! -d $PACKAGE_BASE/$folder ]
    then
       echo "$PACKAGE_BASE/$folder missing" | tee -a $LOG_FILE
       rstatus="FAILED"
     fi
done

if [ "$rstatus" == FAILED ]
then
   echo "$rstatus" | tee -a $LOG_FILE
   exit 1
fi

echo $rstatus | tee -a $LOG_FILE
#Copy binaries and libs to global path
for folder in $DIR_CHECK
do
    echo "Copying $PACKAGE_BASE/$folder/* to $SOFTWARE_BASE/$folder/" | tee -a $LOG_FILE
    cp -pR $PACKAGE_BASE/$folder/* $SOFTWARE_BASE/$folder/
done
exit 0

