#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
# Date: November 2017
# Modified: February 2018
#
# This script is called by the main install script 
# (install_package.sh)  to build and install 
# a new version of the package 
#
# What it does:
# 1) source the main config file to set global path
# 2) untar the downloaded tar file
# 3) Copy executables to SOFTWARE_BIN_BASE
#
# Note: the following environment variables are expected to be set
# by the caller
# 1) GLOBAL_CONFIG
# 2) PACKAGE_BASE
# 3) PACKAGE_DEPENDS
#
cd `dirname $0`
SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`
echo "==" 
echo "Server Name: `uname -n`" 
echo "Install Date: `date`" 
if [ ! -f ../${GLOBAL_CONFIG} ]
then
  echo "'../${GLOBAL_CONFIG}' file missing "     
  exit 1
fi
source ./../${GLOBAL_CONFIG}
if [ "${PACKAGE_DEPENDS}" = "" ]
then
   echo "ERROR: PACKAGE_DEPENDS not set"
   exit 1
fi
PACKAGE_DEPENDENCIES_FILE=`basename ${PACKAGE_DEPENDS}`
source ./${PACKAGE_DEPENDENCIES_FILE}
if [ ! -d ${PACKAGE_BASE} ]
then
   echo "ERROR: Missing the install directory ${PACKAGE_BASE} "
   exit 1
fi
#Check the install
cd ${PACKAGE_BASE} 
if [ ! -d ${GIT_REPOS} ]
then
   echo "ERROR:${PACKAGE_BASE}/${GIT_REPOS} directory missing"
   echo "Status: FAILED"
   exit 1
fi
mv ${GIT_REPOS}/* .
rm -rf ${GIT_REPOS}
if [ ! -f ${BIN_FILE} ]
then
   echo "ERROR: ${BIN_FILE} executable missing from the install: `pwd`"
   exit 1
fi
chmod 755 ${BIN_FILE}
cd ${SOFTWARE_BIN_BASE}
[ -f ${BIN_FILE} ] && rm ${BIN_FILE}

ln -s ${PACKAGE_BASE}/${BIN_FILE} 

echo "Status: SUCCESS"
exit 0

