#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
# Date: November 2017
# Source : https://combine-lab.github.io/salmon/getting_started/#obtaining-salmon
## Script to build and install a new package

cd `dirname $0`

SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`
##These config files are relative to
# the Install script working directory
dependents_file=dependencies.cfg
pack_config_file=fastqc_repos.cfg

if [ ! -f $dependents_file ]
then
   echo "The dependencies file: $dependents_file is missing"
   echo " From $WORKING_DIR"
   exit 1
fi
if [ ! -f ../Configuration ]
then
  echo "'../Configuration' file missing "     
  exit 1
fi
if [ ! -f $1 ]
then
  echo "'$1' file missing"     
  exit 1
fi

source ./../Configuration
source ./$dependents_file
source ./$pack_config_file

if [ ! -f $RELEASE_FILE ]
then
   echo "File $RELEASE_FILE does not exists"
   exit 1
fi

RELEASE_NUMBER=`cat $RELEASE_FILE`
LOG_FILE="${DOWNLOADS_LOG_DIR}/$SCRIPT_NAME.$SHORT_NAME.$RELEASE_NUMBER.log"
PACKAGE_BASE=$LOCAL_DIR/$SHORT_NAME

rm -rf $LOG_FILE
touch $LOG_FILE

rstatus=""
echo "==" | tee -a $LOG_FILE
echo "Product: $GIT_REPOS" | tee -a $LOG_FILE
echo "Install directory: $PACKAGE_BASE" | tee -a $LOG_FILE
echo "Release version: $RELEASE_NUMBER" | tee -a $LOG_FILE
echo "Install on Server Name: `uname -n`" | tee -a $LOG_FILE
echo "==" | tee -a $LOG_FILE

echo "Running the dependency test" | tee -a $LOG_FILE
echo "Missing dependencies:" | tee -a $LOG_FILE
for dependency in $DEPENDENCIES
do
    token=`which $dependency`
    if [ ! -f "$token" ]
    then
       echo "Dependency: $dependency" | tee -a $LOG_FILE
       rstatus="Failed"
    fi
done
echo "==" | tee -a $LOG_FILE
if [ "$rstatus" == Failed ]
then
  echo "Dependency test Failed" | tee -a $LOG_FILE
  exit 1
fi
echo "Dependency test passed" | tee -a $LOG_FILE
echo "Checking the Install directory:" | tee -a $LOG_FILE
# Execute the Install command for this package
#
if [ ! -d $PACKAGE_BASE ]
then
  echo "ERROR:$PACKAGE_BASE directory missing"
  echo "Status: FAILED"
  exit 1
fi
#Check the install
cd $PACKAGE_BASE 
if [ ! -d $GIT_REPOS ]
then
   echo "ERROR:$PACKAGE_BASE/$GIT_REPOS directory missing"
   echo "Status: FAILED"
   exit 1
fi
mv $GIT_REPOS/* .
rm -rf $GIT_REPOS
if [ ! -f $BIN_FILE ]
then
   echo "ERROR: $BIN_FILE executable missing from the install: `pwd`"
   exit 1
fi
chmod 755 $BIN_FILE
cd $SOFTWARE_BASE/bin
[ -f $BIN_FILE ] && rm $BIN_FILE

ln -s $PACKAGE_BASE/$BIN_FILE 

echo "Status: SUCCESS"
exit 0

