#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
# Date: October 2017
# Modified: February 2018
#
# This script is called by the main install script 
# (install_package.sh)  to build and install 
# a new version of the package 
#
# What it does:
# 1) source the main config file to set global path
# 2) untar the downloaded tar file
# 3) builds and install R
#
# Note: the following environment variables are expected to be set
# by the caller
# 1) GLOBAL_CONFIG
# 2) PACKAGE_BASE
# 3) PACKAGE_DEPENDS
#
cd `dirname $0`
SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`
echo "==" 
echo "Server Name: `uname -n`" 
echo "Install Date: `date`" 
if [ ! -f ../${GLOBAL_CONFIG} ]
then
  echo "'../${GLOBAL_CONFIG}' file missing "     
  exit 1
fi
source ./../${GLOBAL_CONFIG}
if [ "${PACKAGE_DEPENDS}" = "" ]
then
   echo "ERROR: PACKAGE_DEPENDS not set"
   exit 1
fi
PACKAGE_DEPENDENCIES_FILE=`basename ${PACKAGE_DEPENDS}`
source ./${PACKAGE_DEPENDENCIES_FILE}
if [ ! -d ${PACKAGE_BASE} ]
then
   echo "ERROR: Missing the install directory ${PACKAGE_BASE} "
   exit 1
fi

cd ${PACKAGE_BASE}
echo "Running the install from "`pwd` 
./configure --prefix=$SOFTWARE_BASE --with-x=no
make
make install

#make install-info
#make install-pdf
exit 0

