#!/bin/sh

# Organization: MDIBL
# Author: Lucie Hutchins
# Date: October 2017
## Script to build and install a new package
cd `dirname $0`
SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`
TAR=`which tar`

if [ ! -f ../${GLOBAL_CONFIG} ]
then
  echo "'../${GLOBAL_CONFIG}' file missing "     
  exit 1
fi
source ./../${GLOBAL_CONFIG}
PACKAGE_CONFIG_FILE=R${PACKAGE_CONFIGFILE_SUFFIX}
source ./${PACKAGE_CONFIG_FILE}
PACKAGE_BASE=${EXTERNAL_SOFTWARE_BASE}/${SHORT_NAME}
if [ ! -d ${PACKAGE_BASE} ]
then
   echo "ERROR: Missing the install directory ${PACKAGE_BASE} "
   exit 1
fi
LOG_FILE="${DOWNLOADS_LOG_DIR}/${SCRIPT_NAME}.${SHORT_NAME}.${RELEASE_NUMBER}.log"

rm -rf ${LOG_FILE}
touch ${LOG_FILE}
rstatus=""
echo "==" | tee -a ${LOG_FILE}
echo "Product: ${SHORT_NAME}" | tee -a ${LOG_FILE}
echo "Install directory: ${PACKAGE_BASE}" | tee -a ${LOG_FILE}
echo "Release version: ${RELEASE_NUMBER}" | tee -a ${LOG_FILE}
echo "Install on Server Name: `uname -n`" | tee -a ${LOG_FILE}
echo "==" | tee -a ${LOG_FILE}
cd ${PACKAGE_BASE}

if [ ! -f ${REMOTE_FILES} ]
then
   echo "ERROR - tar file:${REMOTE_FILES} missing under `pwd`"
   exit 1 
fi
echo "Running ${TAR} -xvf ${REMOTE_FILES} command from "`pwd` | tee -a ${LOG_FILE}
${TAR} -xvf ${REMOTE_FILES} 2>&1 | tee -a $LOG_FILE
if [ ! -d ${RELEASE_DIR} ]
then
   rstatus="FAILED"
   echo "Command $TAR -xvf $REMOTE_FILES failed - missing directory ${RELEASE_DIR}"
   exit 1
fi
#cleanup the tar file
rm -f $REMOTE_FILES
cd ${RELEASE_DIR}
echo "Running the install from "`pwd` | tee -a $LOG_FILE
./configure --prefix=$SOFTWARE_BASE --with-x=no
make
make install
#make install-info
#make install-pdf
exit 0

